version: "3.7"

services: #says what are we gonna orchestrate
    #backend
    restful_api:
        container_name: backend
        build: ./ 
        command: node index.js
        working_dir: /usr/src/RESTFUL_API
        environment:
            NODE_ENV: staging
            FROMPHONE: "+12054309818"
            SID: AC56c10132249533ecd36a8dba4e1f0952
            TOKEN: 887eeccc3984239de9460c8b8dd8341c
            
        ports:
            - "3000:3000"
        volumes:
            - ./:/usr/src/RESTFUL_API
   
